{
  "url": "https://api.github.com/repos/shap/shap/issues/1387",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/1387/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/1387/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/1387/events",
  "html_url": "https://github.com/shap/shap/issues/1387",
  "id": 688281516,
  "node_id": "MDU6SXNzdWU2ODgyODE1MTY=",
  "number": 1387,
  "title": "Getting py4j error on shap 0.36 and spark 2.x",
  "user": {
    "login": "ashishjwr",
    "id": 4239021,
    "node_id": "MDQ6VXNlcjQyMzkwMjE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4239021?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ashishjwr",
    "html_url": "https://github.com/ashishjwr",
    "followers_url": "https://api.github.com/users/ashishjwr/followers",
    "following_url": "https://api.github.com/users/ashishjwr/following{/other_user}",
    "gists_url": "https://api.github.com/users/ashishjwr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ashishjwr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ashishjwr/subscriptions",
    "organizations_url": "https://api.github.com/users/ashishjwr/orgs",
    "repos_url": "https://api.github.com/users/ashishjwr/repos",
    "events_url": "https://api.github.com/users/ashishjwr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ashishjwr/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2020-08-28T18:36:56Z",
  "updated_at": "2021-03-11T22:27:18Z",
  "closed_at": "2021-03-11T22:27:18Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I installed SHAP 0.36. It only works with spark 3.0 ( py4j 0.10.9). Can we also have support for spark 2.x ( which uses py4j 0.10.7) ? I get the following error with Spark 2.4.5 and SHAP 0.36\r\n\r\n```\r\nERROR:root:Exception while sending command.\r\nTraceback (most recent call last):\r\n  File \"C:\\Python37\\lib\\site-packages\\py4j\\java_gateway.py\", line 1152, in send_command\r\n    answer = smart_decode(self.stream.readline()[:-1])\r\n  File \"C:\\Python37\\lib\\socket.py\", line 589, in readinto\r\n    return self._sock.recv_into(b)\r\nConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\r\n```",
  "closed_by": {
    "login": "ashishjwr",
    "id": 4239021,
    "node_id": "MDQ6VXNlcjQyMzkwMjE=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4239021?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ashishjwr",
    "html_url": "https://github.com/ashishjwr",
    "followers_url": "https://api.github.com/users/ashishjwr/followers",
    "following_url": "https://api.github.com/users/ashishjwr/following{/other_user}",
    "gists_url": "https://api.github.com/users/ashishjwr/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ashishjwr/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ashishjwr/subscriptions",
    "organizations_url": "https://api.github.com/users/ashishjwr/orgs",
    "repos_url": "https://api.github.com/users/ashishjwr/repos",
    "events_url": "https://api.github.com/users/ashishjwr/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ashishjwr/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/1387/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/1387/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
