{
  "url": "https://api.github.com/repos/shap/shap/issues/1419",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/1419/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/1419/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/1419/events",
  "html_url": "https://github.com/shap/shap/issues/1419",
  "id": 697719791,
  "node_id": "MDU6SXNzdWU2OTc3MTk3OTE=",
  "number": 1419,
  "title": "Unrecognized model_output parameter value: predict_proba with TreeExplainer and scikit RandomForestClassifier",
  "user": {
    "login": "SerissaDahoe",
    "id": 39773727,
    "node_id": "MDQ6VXNlcjM5NzczNzI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/39773727?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SerissaDahoe",
    "html_url": "https://github.com/SerissaDahoe",
    "followers_url": "https://api.github.com/users/SerissaDahoe/followers",
    "following_url": "https://api.github.com/users/SerissaDahoe/following{/other_user}",
    "gists_url": "https://api.github.com/users/SerissaDahoe/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SerissaDahoe/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SerissaDahoe/subscriptions",
    "organizations_url": "https://api.github.com/users/SerissaDahoe/orgs",
    "repos_url": "https://api.github.com/users/SerissaDahoe/repos",
    "events_url": "https://api.github.com/users/SerissaDahoe/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SerissaDahoe/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 3,
  "created_at": "2020-09-10T10:11:12Z",
  "updated_at": "2020-09-14T20:38:59Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hi,\r\n\r\nI was trying to use the TreeExplainer on a scikit Random Forest model, with the predict_proba function, even mentioned as an example in the docs here:\r\n<img width=\"708\" alt=\"image\" src=\"https://user-images.githubusercontent.com/39773727/92715712-23200d80-f35e-11ea-838c-4c8f8287b6cf.png\">\r\n\r\nI'm using below code:\r\n```\r\nimport shap\r\nfrom sklearn import datasets\r\nfrom sklearn.ensemble import RandomForestClassifier\r\n\r\niris = datasets.load_iris()\r\nX = iris.data[:, :2]  # we only take the first two features.\r\ny = iris.target\r\nmodel = RandomForestClassifier()\r\nmodel.fit(X, y);\r\ny_pred = model.predict_proba(X)\r\n\r\nexplainer = shap.TreeExplainer(model, feature_perturbation='interventional', \r\n                               model_output=\"predict_proba\", data=X)\r\nshap_values = explainer.shap_values(X)\r\n```\r\n\r\nAnd getting the following exception:\r\n<img width=\"735\" alt=\"image\" src=\"https://user-images.githubusercontent.com/39773727/92715955-74c89800-f35e-11ea-9a3c-88f72e9c7666.png\">\r\n\r\nHas anyone else had a similar issue, or knows how to fix it?",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/1419/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/1419/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
