{
  "url": "https://api.github.com/repos/shap/shap/issues/1695",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/1695/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/1695/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/1695/events",
  "html_url": "https://github.com/shap/shap/issues/1695",
  "id": 774111922,
  "node_id": "MDU6SXNzdWU3NzQxMTE5MjI=",
  "number": 1695,
  "title": "shap 0.37.0 shap.Explainer bug",
  "user": {
    "login": "bvaidyan",
    "id": 37364927,
    "node_id": "MDQ6VXNlcjM3MzY0OTI3",
    "avatar_url": "https://avatars.githubusercontent.com/u/37364927?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bvaidyan",
    "html_url": "https://github.com/bvaidyan",
    "followers_url": "https://api.github.com/users/bvaidyan/followers",
    "following_url": "https://api.github.com/users/bvaidyan/following{/other_user}",
    "gists_url": "https://api.github.com/users/bvaidyan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bvaidyan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bvaidyan/subscriptions",
    "organizations_url": "https://api.github.com/users/bvaidyan/orgs",
    "repos_url": "https://api.github.com/users/bvaidyan/repos",
    "events_url": "https://api.github.com/users/bvaidyan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bvaidyan/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2020-12-24T00:45:11Z",
  "updated_at": "2020-12-28T09:11:54Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "When I ran the example code from below link (using shap version 0.37.0) \r\n\r\nhttps://github.com/slundberg/shap/blob/master/notebooks/text_examples/sentiment_analysis/text_to_multiclass_explanations/Emotion%20Classification%20Explanation%20Demo.ipynb\r\n\r\nI got below error while using shap.Explainer.\r\n\r\nexplainer = shap.Explainer(f, tokenizer, output_names=labels)\r\n**---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-22-1612029beb1e> in <module>\r\n----> 1 explainer = shap.Explainer(f, tokenizer, output_names=labels)\r\n\r\n/usr/local/lib/python3.8/dist-packages/shap/explainers/_explainer.py in __init__(self, model, masker, link, algorithm, output_names, feature_names, **kwargs)\r\n    139             elif algorithm == \"partition\":\r\n    140                 self.__class__ = explainers.Partition\r\n--> 141                 explainers.Partition.__init__(self, model, self.masker, link=self.link, feature_names=self.feature_names, output_names=self.output_names, **kwargs)\r\n    142             elif algorithm == \"tree\":\r\n    143                 self.__class__ = explainers.Tree\r\n\r\nTypeError: __init__() got an unexpected keyword argument 'feature_names'**\r\n\r\n\r\nI even tried shap 0.36.0 to see if the error would go away and it did, but later got stuck in the next step where this below statement is executed.\r\n\r\nshap_values_multiclass = explainer(data['text'][0:50])\r\n\r\n**---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\nTypeError: only size-1 arrays can be converted to Python scalars\r\n\r\nThe above exception was the direct cause of the following exception:\r\n\r\nValueError                                Traceback (most recent call last)\r\n<ipython-input-11-9220750e7570> in <module>\r\n----> 1 shap_values_multiclass = explainer(data['text'][0:50])\r\n\r\n/usr/local/lib/python3.8/dist-packages/shap/explainers/_explainer.py in __call__(self, max_evals, main_effects, error_bounds, batch_size, outputs, silent, *args, **kwargs)\r\n    194             feature_names = [[] for _ in range(len(args))]\r\n    195         for row_args in show_progress(zip(*args), num_rows, self.__class__.__name__+\" explainer\", silent):\r\n--> 196             row_result = self.explain_row(\r\n    197                 *row_args, max_evals=max_evals, main_effects=main_effects, error_bounds=error_bounds,\r\n    198                 batch_size=batch_size, silent=silent, **kwargs\r\n\r\n/usr/local/lib/python3.8/dist-packages/shap/explainers/_partition.py in explain_row(self, max_evals, main_effects, error_bounds, batch_size, silent, *row_args)\r\n    452         output_indexes = None\r\n    453         fixed_context = 1\r\n--> 454         output_indexes, base_value = self.owen(fm, max_evals // 2, output_indexes, fixed_context, batch_size, silent)\r\n    455 \r\n    456         if False:\r\n\r\n/usr/local/lib/python3.8/dist-packages/shap/explainers/_partition.py in owen(self, fm, npartitions, output_indexes, fixed_context, batch_size, silent)\r\n    592                     self.dvalues[ind] += (f11 - f10 - f01 + f00) * weight # leave the interaction effect on the internal node\r\n    593                 elif fixed_context == 1:\r\n--> 594                     self.dvalues[ind] -= (f11 - f10 - f01 + f00) * weight # leave the interaction effect on the internal node\r\n    595 \r\n    596                 if fixed_context is None or fixed_context == 0:\r\n\r\nValueError: setting an array element with a sequence.**\r\n\r\n\r\nKindly help.\r\n\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/1695/reactions",
    "total_count": 1,
    "+1": 1,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/1695/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
