{
  "url": "https://api.github.com/repos/shap/shap/issues/1969",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/1969/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/1969/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/1969/events",
  "html_url": "https://github.com/shap/shap/issues/1969",
  "id": 872584242,
  "node_id": "MDU6SXNzdWU4NzI1ODQyNDI=",
  "number": 1969,
  "title": "AssertionError when only explaining one image",
  "user": {
    "login": "trannel",
    "id": 43033261,
    "node_id": "MDQ6VXNlcjQzMDMzMjYx",
    "avatar_url": "https://avatars.githubusercontent.com/u/43033261?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/trannel",
    "html_url": "https://github.com/trannel",
    "followers_url": "https://api.github.com/users/trannel/followers",
    "following_url": "https://api.github.com/users/trannel/following{/other_user}",
    "gists_url": "https://api.github.com/users/trannel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/trannel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/trannel/subscriptions",
    "organizations_url": "https://api.github.com/users/trannel/orgs",
    "repos_url": "https://api.github.com/users/trannel/repos",
    "events_url": "https://api.github.com/users/trannel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/trannel/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2021-04-30T14:12:17Z",
  "updated_at": "2021-07-14T07:00:34Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "When I try to explain only one image (a numpy array with the shape (1, x, x, 3), see the example) with shap it will throw the following error:\r\n```\r\n  File \"/.../shap_test/venv/lib/python3.7/site-packages/shap/plots/_image.py\", line 73, in image\r\n    assert labels.shape[0] == shap_values[0].shape[0], \"Labels must have same row count as shap_values arrays!\"\r\nAssertionError: Labels must have same row count as shap_values arrays!\r\n```\r\nExplaining 2 images works fine as the example below will show. The only difference is the value of the first parameter in the shape of the input, which determines how many images are in the array.\r\n\r\nExample: First we run shap with an array filled with 2 images, which works as intended. Next we only use one image, which will fail and throw the mentioned error.\r\n```python\r\nimport numpy as np\r\nimport shap\r\nimport random\r\n\r\ndef predict(imgs_np):\r\n    rand = random.uniform(0, 1)\r\n    result = [[rand, 1-rand]]\r\n    # result = [[0.6, 0.4]]\r\n    return result\r\n\r\ndef explain(imgs_np):\r\n    masker = shap.maskers.Image(\"inpaint_telea\", imgs_np[0].shape)\r\n    explainer = shap.Explainer(predict, masker, output_names=[\"good\", \"bad\"])\r\n    shap_values = explainer(imgs_np, max_evals=4, batch_size=1, outputs=shap.Explanation.argsort.flip[:])\r\n    shap.image_plot(shap_values)\r\n\r\nif __name__ == '__main__':\r\n    random.seed(0)\r\n    np.random.seed(0)\r\n    img_np_2 = np.random.rand(2, 5, 5, 3)\r\n    explain(img_np_2)\r\n    img_np_1 = np.random.rand(1, 5, 5, 3)\r\n    explain(img_np_1)\r\n```\r\n\r\nThe cause for this seems to be in shap/explainers/_explainer.py line 308-310. Removing these following lines will make the example also run for only one image:\r\n```python\r\nif isinstance(sliced_labels, np.ndarray) and len(sliced_labels.shape) == 2:\r\n    if np.all(sliced_labels[0,:] == sliced_labels):\r\n        sliced_labels = sliced_labels[0]\r\n```\r\n\r\nRemoving those lines will also fix another issue. When I uncomment the commented out line in `predict` it will no longer throw the following error:\r\n```\r\n  File \"/.../shap_test/venv/lib/python3.7/site-packages/shap/plots/_image.py\", line 75, in image\r\n    assert labels.shape[1] == len(shap_values), \"Labels must have a column for each output in shap_values!\"\r\nIndexError: tuple index out of range\r\n```\r\nIt seems like in cases where all predictions are the same, like when I only explain one image, shap will remove one dimension in the explainer, which will later cause errors while plotting.\r\n\r\nLibraries installed:\r\nshap 0.39.0\r\nopencv_python 4.5.1.48\r\nmatplotlib 3.4.1\r\nipython 7.22.0",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/1969/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/1969/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
