{
  "url": "https://api.github.com/repos/shap/shap/issues/2021",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2021/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2021/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2021/events",
  "html_url": "https://github.com/shap/shap/issues/2021",
  "id": 908109850,
  "node_id": "MDU6SXNzdWU5MDgxMDk4NTA=",
  "number": 2021,
  "title": "AttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'",
  "user": {
    "login": "sezanel",
    "id": 76706617,
    "node_id": "MDQ6VXNlcjc2NzA2NjE3",
    "avatar_url": "https://avatars.githubusercontent.com/u/76706617?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sezanel",
    "html_url": "https://github.com/sezanel",
    "followers_url": "https://api.github.com/users/sezanel/followers",
    "following_url": "https://api.github.com/users/sezanel/following{/other_user}",
    "gists_url": "https://api.github.com/users/sezanel/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sezanel/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sezanel/subscriptions",
    "organizations_url": "https://api.github.com/users/sezanel/orgs",
    "repos_url": "https://api.github.com/users/sezanel/repos",
    "events_url": "https://api.github.com/users/sezanel/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sezanel/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2021-06-01T09:44:37Z",
  "updated_at": "2021-10-26T03:26:09Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hi! \r\n\r\nI have never used SHAP before. I am using the following keras and tesnorflow version:\r\nkeras version 2.6.0\r\ntensdorflow version 2.6.0-dev20210418\r\n\r\nI load my model (CNN) and my database and when I execute SHAB I have the following error:\r\n\r\nAttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'\r\n\r\nHere the code:\r\n        import shap\r\n\timport pdb; pdb.set_trace()\r\n\t#tf.compat.v1.disable_eager_execution()\r\n\tbackground = xtrain[np.random.choice(xtrain.shape[0], 100, replace=False)]\r\n\texplainer = shap.DeepExplainer(model,background)\r\n\tshap_values = explainer.shap_values(xtest[1:5])\r\n\tshap.image_plot(shap_values, -xtest[1:5])\r\n\r\n\r\n \r\nHere the error:\r\n\r\nshap_values = explainer.shap_values(xtest[1:5])\r\n*** AttributeError: in user code:\r\n\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\shap\\explainers\\_deep\\deep_tf.py:243 grad_graph  *\r\n        out = self.model(shap_rAnD)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\engine\\base_layer.py:1005 __call__  **\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\engine\\sequential.py:374 call\r\n        return super(Sequential, self).call(inputs, training=training, mask=mask)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\engine\\functional.py:414 call\r\n        return self._run_internal_graph(\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\engine\\functional.py:550 _run_internal_graph\r\n        outputs = node.layer(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\engine\\base_layer.py:1005 __call__\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\keras\\layers\\convolutional.py:245 call\r\n        outputs = self._convolution_op(inputs, self.kernel)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\r\n        return target(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\nn_ops.py:1131 convolution_v2\r\n        return convolution_internal(\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\nn_ops.py:1261 convolution_internal\r\n        return op(\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\r\n        return target(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:602 new_func\r\n        return func(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:602 new_func\r\n        return func(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\nn_ops.py:2000 conv1d\r\n        value = array_ops.expand_dims(value, spatial_start_dim)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\r\n        return target(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\deprecation.py:535 new_func\r\n        return func(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py:366 expand_dims\r\n        return expand_dims_v2(input, axis, name)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py:206 wrapper\r\n        return target(*args, **kwargs)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\array_ops.py:436 expand_dims_v2\r\n        return gen_array_ops.expand_dims(input, axis, name)\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\tensorflow\\python\\ops\\gen_array_ops.py:2304 expand_dims\r\n        _execute.record_gradient(\r\n    C:\\Users\\zanel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\shap\\explainers\\_deep\\deep_tf.py:26 custom_record_gradient\r\n        out = tf_backprop._record_gradient(\"shap_\"+op_name, inputs, attrs, results)\r\n\r\n    AttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'\r\n\r\n\r\nI have already tried tf.compat.v1.disable_eager_execution() but then I have another error. \r\n\r\nCould you please help me?\r\n\r\nThank you!\r\n\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2021/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2021/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
