{
  "url": "https://api.github.com/repos/shap/shap/issues/206",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/206/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/206/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/206/events",
  "html_url": "https://github.com/shap/shap/issues/206",
  "id": 348645729,
  "node_id": "MDU6SXNzdWUzNDg2NDU3Mjk=",
  "number": 206,
  "title": "Cannot import shap",
  "user": {
    "login": "uriel-vinetz-rf",
    "id": 33449706,
    "node_id": "MDQ6VXNlcjMzNDQ5NzA2",
    "avatar_url": "https://avatars.githubusercontent.com/u/33449706?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/uriel-vinetz-rf",
    "html_url": "https://github.com/uriel-vinetz-rf",
    "followers_url": "https://api.github.com/users/uriel-vinetz-rf/followers",
    "following_url": "https://api.github.com/users/uriel-vinetz-rf/following{/other_user}",
    "gists_url": "https://api.github.com/users/uriel-vinetz-rf/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/uriel-vinetz-rf/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/uriel-vinetz-rf/subscriptions",
    "organizations_url": "https://api.github.com/users/uriel-vinetz-rf/orgs",
    "repos_url": "https://api.github.com/users/uriel-vinetz-rf/repos",
    "events_url": "https://api.github.com/users/uriel-vinetz-rf/events{/privacy}",
    "received_events_url": "https://api.github.com/users/uriel-vinetz-rf/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 15,
  "created_at": "2018-08-08T09:28:11Z",
  "updated_at": "2021-10-14T02:05:32Z",
  "closed_at": "2018-08-08T15:28:32Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hi,\r\n\r\n@slundberg  .I can't import shap either on python 3.5 on Ubuntu and 3.6 on Windows. In both cases (after installing with 'pip install shap') I get the following error:\r\n\r\nImportError                               Traceback (most recent call last)\r\n<ipython-input-42-efbb001a1501> in <module>()\r\n----> 1 import shap\r\n\r\n~/data/dev/lib/python3.5/site-packages/shap/__init__.py in <module>()\r\n     12 from .plots.image import image_plot\r\n     13 from . import datasets\r\n---> 14 from . import benchmark\r\n     15 from .explainers import other\r\n\r\nImportError: cannot import name 'benchmark'",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/206/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/206/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
