{
  "url": "https://api.github.com/repos/shap/shap/issues/2361",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/2361/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/2361/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/2361/events",
  "html_url": "https://github.com/shap/shap/issues/2361",
  "id": 1112569786,
  "node_id": "I_kwDOBHDcK85CUHe6",
  "number": 2361,
  "title": "File descriptor not closed in CatBoostTreeModelLoader ctor",
  "user": {
    "login": "nieksand",
    "id": 1396037,
    "node_id": "MDQ6VXNlcjEzOTYwMzc=",
    "avatar_url": "https://avatars.githubusercontent.com/u/1396037?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nieksand",
    "html_url": "https://github.com/nieksand",
    "followers_url": "https://api.github.com/users/nieksand/followers",
    "following_url": "https://api.github.com/users/nieksand/following{/other_user}",
    "gists_url": "https://api.github.com/users/nieksand/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nieksand/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nieksand/subscriptions",
    "organizations_url": "https://api.github.com/users/nieksand/orgs",
    "repos_url": "https://api.github.com/users/nieksand/repos",
    "events_url": "https://api.github.com/users/nieksand/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nieksand/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2022-01-24T12:15:33Z",
  "updated_at": "2022-01-24T12:15:33Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I was getting the following warnings via Python's unit test library:\r\n```\r\nunclosed file <_io.TextIOWrapper name='/tmp/tmpbwbd1dwm' mode='r' encoding='UTF-8'>\r\n```\r\n\r\nI traced the issue to https://github.com/slundberg/shap/blob/9d7de4dee742ce10684400171257c66a86e4c7a6/shap/explainers/_tree.py#L1584\r\n```\r\nclass CatBoostTreeModelLoader:\r\n    def __init__(self, cb_model):\r\n        # cb_model.save_model(\"cb_model.json\", format=\"json\")\r\n        # self.loaded_cb_model = json.load(open(\"cb_model.json\", \"r\"))\r\n        import tempfile\r\n        tmp_file = tempfile.NamedTemporaryFile()\r\n        cb_model.save_model(tmp_file.name, format=\"json\")\r\n        self.loaded_cb_model = json.load(open(tmp_file.name, \"r\"))\r\n        tmp_file.close()\r\n```\r\n\r\nNote the `open()` call inside `json.load()` without a context manager or corresponding `close()`.\r\n\r\nCpython will probably close this descriptor when it ref counts, but the Python docs explicitly warn you not to do this:\r\n\r\n> Other implementations act differently and CPython may change. Do not depend on immediate finalization of objects when they become unreachable (so you should always close files explicitly).\r\n\r\nhttps://docs.python.org/3/reference/datamodel.html#objects-values-and-types.\r\n\r\nI am not familiar with shap, but the fix is probably calling json.load() on the already file-like `tmp_file` directly:\r\n```\r\n        self.loaded_cb_model = json.load(tmp_file)\r\n```",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/2361/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/2361/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
