{
  "url": "https://api.github.com/repos/shap/shap/issues/29",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/29/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/29/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/29/events",
  "html_url": "https://github.com/shap/shap/issues/29",
  "id": 293546481,
  "node_id": "MDU6SXNzdWUyOTM1NDY0ODE=",
  "number": 29,
  "title": "Output value in binary classification task is outside [0, 1] range",
  "user": {
    "login": "asstergi",
    "id": 9599766,
    "node_id": "MDQ6VXNlcjk1OTk3NjY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/9599766?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/asstergi",
    "html_url": "https://github.com/asstergi",
    "followers_url": "https://api.github.com/users/asstergi/followers",
    "following_url": "https://api.github.com/users/asstergi/following{/other_user}",
    "gists_url": "https://api.github.com/users/asstergi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/asstergi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/asstergi/subscriptions",
    "organizations_url": "https://api.github.com/users/asstergi/orgs",
    "repos_url": "https://api.github.com/users/asstergi/repos",
    "events_url": "https://api.github.com/users/asstergi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/asstergi/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 40,
  "created_at": "2018-02-01T14:18:16Z",
  "updated_at": "2022-06-06T18:18:45Z",
  "closed_at": "2018-02-01T16:57:08Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hi @slundberg,\r\n\r\nI've been playing with a binary classification task using XGBoost and I noticed an unexpected (for me at least) behaviour. I replicated it using the `adult` dataset you're providing. \r\n\r\nSo, after training a binary classfication XGBoost model and plotting the SHAP values for a case, I'm getting the following:\r\n\r\n![image](https://user-images.githubusercontent.com/9599766/35682997-4304d52c-076b-11e8-9884-c53cdc1f8a9c.png)\r\n\r\nBoth the base value and the output value are outside the [0, 1] range. Is this the expected bahavior? If so, how can someone interpret this?",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/29/reactions",
    "total_count": 9,
    "+1": 9,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/29/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
