{
  "url": "https://api.github.com/repos/shap/shap/issues/3172",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/3172/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/3172/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/3172/events",
  "html_url": "https://github.com/shap/shap/issues/3172",
  "id": 1830932356,
  "node_id": "I_kwDOBHDcK85tIc-E",
  "number": 3172,
  "title": "BUG: waterfall plot bug for sklearn RandomForestClassifier",
  "user": {
    "login": "fountaindive",
    "id": 91950069,
    "node_id": "U_kgDOBXsL9Q",
    "avatar_url": "https://avatars.githubusercontent.com/u/91950069?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fountaindive",
    "html_url": "https://github.com/fountaindive",
    "followers_url": "https://api.github.com/users/fountaindive/followers",
    "following_url": "https://api.github.com/users/fountaindive/following{/other_user}",
    "gists_url": "https://api.github.com/users/fountaindive/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fountaindive/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fountaindive/subscriptions",
    "organizations_url": "https://api.github.com/users/fountaindive/orgs",
    "repos_url": "https://api.github.com/users/fountaindive/repos",
    "events_url": "https://api.github.com/users/fountaindive/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fountaindive/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 486901329,
      "node_id": "MDU6TGFiZWw0ODY5MDEzMjk=",
      "url": "https://api.github.com/repos/shap/shap/labels/bug",
      "name": "bug",
      "color": "ee0701",
      "default": true,
      "description": "Indicates an unexpected problem or unintended behaviour"
    }
  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2023-08-01T10:13:54Z",
  "updated_at": "2023-08-04T14:49:50Z",
  "closed_at": "2023-08-04T14:49:49Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "### Issue Description\n\nI think this is a similar bug to https://github.com/shap/shap/issues/3129 (fixed in https://github.com/shap/shap/pull/3138)\r\n\r\nWhen trying to use `shap.plots.waterfall` on a `sklearn.ensemble.RandomForestClassifier` model I get the following error:\r\n\r\n```\r\nValueError: The waterfall plot can currently only plot a single explanation, but a matrix of explanations (shape (2, 2)) was passed! Perhaps try `shap.plots.waterfall(shap_values[0])` or for multi-output models, try `shap.plots.waterfall(shap_values[0, 0])`.\r\n```\r\n\r\nUpon examining the output of `explainer(X)` I noticed that the `.values` and `.base_values` potentially have an extra dimension. Could this come from using `model.predict_proba` which outputs two numbers in a binary classification setting, the first is the score for class 0 and the second is the score for class 1?\r\n\r\nThanks for any help!\n\n### Minimal Reproducible Example\n\n```python\nimport pandas as pd\r\nimport shap\r\nfrom sklearn.ensemble import RandomForestClassifier\r\n\r\nX = pd.DataFrame({\"A\": [1, 2, 3], \"B\": [2, 1, 3]})\r\ny = pd.Series([1, 0, 0])\r\n\r\nmodel = RandomForestClassifier(n_estimators=2, max_depth=2, random_state=1)\r\nmodel.fit(X, y)\r\n\r\nexplainer = shap.TreeExplainer(model)\r\nexplanation = explainer(X)\r\n\r\nshap.plots.waterfall(explanation[0])  # this line generates the exception\n```\n\n\n### Expected Behavior\n\nThe expected behaviour is a waterfall plot.\r\n\r\nI was able to produce a waterfall plot if I make the following changes however, I'm not sure this is correct.\r\n\r\n```\r\n# code above is the same\r\nexplanation = explainer(X)\r\n\r\n# two new lines\r\nexplanation.values = explanation.values[:,:,0]\r\nexplanation.base_values = explanation.base_values[0,1]\r\n\r\nshap.plots.waterfall(explanation[0])\r\n```\r\n\r\n\n\n### Bug report checklist\n\n- [X] I have checked that this issue has not already been reported.\n- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.\n- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.\n- [ ] I'd be interested in making a PR to fix this bug\n\n### Installed Versions\n\nI have tried this on `0.42.1` and using `master` as of today (1/8/23)",
  "closed_by": {
    "login": "fountaindive",
    "id": 91950069,
    "node_id": "U_kgDOBXsL9Q",
    "avatar_url": "https://avatars.githubusercontent.com/u/91950069?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/fountaindive",
    "html_url": "https://github.com/fountaindive",
    "followers_url": "https://api.github.com/users/fountaindive/followers",
    "following_url": "https://api.github.com/users/fountaindive/following{/other_user}",
    "gists_url": "https://api.github.com/users/fountaindive/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/fountaindive/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/fountaindive/subscriptions",
    "organizations_url": "https://api.github.com/users/fountaindive/orgs",
    "repos_url": "https://api.github.com/users/fountaindive/repos",
    "events_url": "https://api.github.com/users/fountaindive/events{/privacy}",
    "received_events_url": "https://api.github.com/users/fountaindive/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/3172/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/3172/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
