{
  "url": "https://api.github.com/repos/shap/shap/issues/453",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/453/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/453/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/453/events",
  "html_url": "https://github.com/shap/shap/issues/453",
  "id": 412572089,
  "node_id": "MDU6SXNzdWU0MTI1NzIwODk=",
  "number": 453,
  "title": "IndexError in shap summary plot",
  "user": {
    "login": "Mark531",
    "id": 17707763,
    "node_id": "MDQ6VXNlcjE3NzA3NzYz",
    "avatar_url": "https://avatars.githubusercontent.com/u/17707763?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Mark531",
    "html_url": "https://github.com/Mark531",
    "followers_url": "https://api.github.com/users/Mark531/followers",
    "following_url": "https://api.github.com/users/Mark531/following{/other_user}",
    "gists_url": "https://api.github.com/users/Mark531/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Mark531/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Mark531/subscriptions",
    "organizations_url": "https://api.github.com/users/Mark531/orgs",
    "repos_url": "https://api.github.com/users/Mark531/repos",
    "events_url": "https://api.github.com/users/Mark531/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Mark531/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 12,
  "created_at": "2019-02-20T18:42:46Z",
  "updated_at": "2019-11-01T00:05:17Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "Hello,\r\n\r\nI've just installed a fresh version of shap (0.27.0) with:\r\n> conda install -c conda-forge shap\r\n\r\nAnd I tried to display the global feature importance on a neural network:\r\n```\r\nimport shap\r\n\r\nexplainer = shap.DeepExplainer(model, X)\r\nshap_values = explainer.shap_values(X)\r\nshap.summary_plot(shap_values, X)\r\n```\r\n\r\nBut I get:\r\n> Traceback (most recent call last):\r\n> \r\n>   File \"<ipython-input-159-6e791dffc370>\", line 1, in <module>\r\n>     shap.summary_plot(shap_values, X)\r\n> \r\n>   File \"C:\\Users\\I328807\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\shap\\plots\\summary.py\", line 357, in summary_plot\r\n>     y_pos, global_shap_values[feature_inds], 0.7, left=left_pos, align='center',\r\n> \r\n> IndexError: index 56 is out of bounds for axis 0 with size 1\r\n\r\nIs it related to an outdated dependency package?\r\n\r\nMark",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/453/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/453/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
