{
  "url": "https://api.github.com/repos/shap/shap/issues/625",
  "repository_url": "https://api.github.com/repos/shap/shap",
  "labels_url": "https://api.github.com/repos/shap/shap/issues/625/labels{/name}",
  "comments_url": "https://api.github.com/repos/shap/shap/issues/625/comments",
  "events_url": "https://api.github.com/repos/shap/shap/issues/625/events",
  "html_url": "https://github.com/shap/shap/issues/625",
  "id": 450824551,
  "node_id": "MDU6SXNzdWU0NTA4MjQ1NTE=",
  "number": 625,
  "title": "strange matplotlib force plots",
  "user": {
    "login": "cbeauhilton",
    "id": 34774299,
    "node_id": "MDQ6VXNlcjM0Nzc0Mjk5",
    "avatar_url": "https://avatars.githubusercontent.com/u/34774299?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/cbeauhilton",
    "html_url": "https://github.com/cbeauhilton",
    "followers_url": "https://api.github.com/users/cbeauhilton/followers",
    "following_url": "https://api.github.com/users/cbeauhilton/following{/other_user}",
    "gists_url": "https://api.github.com/users/cbeauhilton/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/cbeauhilton/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/cbeauhilton/subscriptions",
    "organizations_url": "https://api.github.com/users/cbeauhilton/orgs",
    "repos_url": "https://api.github.com/users/cbeauhilton/repos",
    "events_url": "https://api.github.com/users/cbeauhilton/events{/privacy}",
    "received_events_url": "https://api.github.com/users/cbeauhilton/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2019-05-31T14:23:20Z",
  "updated_at": "2019-12-12T18:29:03Z",
  "closed_at": "2019-12-12T18:29:03Z",
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "I'm having a strange recurrent issue with the matplotlib force plots. See the image for an example - the text rotation seems to start at the wrong place, leading to the text overrunning the graph.\r\n\r\n![SHAP_forceplot](https://user-images.githubusercontent.com/34774299/58711642-f294aa00-838c-11e9-814c-8248b4a9cb2d.png)\r\n\r\n```\r\npython 3.7.3\r\nshap 0.28.5\r\nmatplotlib 3.1.0\r\n```\r\n\r\nHere's the code that made that example:\r\n\r\n```python\r\n shap.force_plot(\r\n                            expected_value,  \r\n                            shap_values[pt_num, :],\r\n                            features_shap.iloc[\r\n                                pt_num, :\r\n                            ],  \r\n                            text_rotation=15,  \r\n                            matplotlib=True,  # instead of Javascript\r\n                            show=False,  \r\n                            link=\"logit\",\r\n                            feature_names=features_shap.columns,\r\n                        )\r\n                        plt.savefig(\r\n                            (title),\r\n                            dpi=1200,\r\n                            transparent=True,\r\n                            bbox_inches=\"tight\",\r\n                            format='png',\r\n                        )\r\n```\r\nI thought maybe my mpl rcParams had gotten screwed up, so I made a fresh Conda environment with basically only shap and its dependencies. I also tried making the images inline in a Jupyter notebook rather than from vanilla .py files, and outputting to various filetypes (png, pdf, ps, etc.), tried all of the mpl backends, but it's the same. The JS plots are fine. \r\n\r\nIs anyone else having this issue? It cropped up rather unexpectedly a few days ago, and I'm not sure what I could have changed that would have caused this.\r\n\r\nThanks! \r\n",
  "closed_by": {
    "login": "slundberg",
    "id": 3740613,
    "node_id": "MDQ6VXNlcjM3NDA2MTM=",
    "avatar_url": "https://avatars.githubusercontent.com/u/3740613?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/slundberg",
    "html_url": "https://github.com/slundberg",
    "followers_url": "https://api.github.com/users/slundberg/followers",
    "following_url": "https://api.github.com/users/slundberg/following{/other_user}",
    "gists_url": "https://api.github.com/users/slundberg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/slundberg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/slundberg/subscriptions",
    "organizations_url": "https://api.github.com/users/slundberg/orgs",
    "repos_url": "https://api.github.com/users/slundberg/repos",
    "events_url": "https://api.github.com/users/slundberg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/slundberg/received_events",
    "type": "User",
    "site_admin": false
  },
  "reactions": {
    "url": "https://api.github.com/repos/shap/shap/issues/625/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/shap/shap/issues/625/timeline",
  "performed_via_github_app": null,
  "state_reason": "completed"
}
